apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db-templatelabel
  serviceName: auth-db
  template:
    metadata:
      labels:
        app: auth-db-templatelabel
    spec:
      containers:
      - image: mongo:7.0-rc-jammy
        name: auth-db
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: azlan
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        - name: MONGO_INITDB_DATABASE
          value: orderDb
        volumeMounts:
        - name: auth-db-storage
          mountPath: /data/db
      volumes:
      - name: auth-db-storage
        persistentVolumeClaim:
          claimName: auth-db-pvc
