apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    name: order-service-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-templatelabel
  template:
    metadata:
      labels:
        app: order-service-templatelabel
    spec:
      containers:
      - image: salif04/order-service:1.0.1
        name: order-service
        resources:
          requests:
            cpu: "0.2"
            memory: "216Mi"
          limits:
            cpu: "1"
            memory: 512Mi
        env:
        - name: PORT
          value: "3000"
        - name: MONGOCONNECTIONURI
          value: mongodb://azlan:password@order-db:27017
        - name: AUTH_URI
          value: http://auth-service
