apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    name: auth-service-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-templatelabel
  template:
    metadata:
      labels:
        app: auth-service-templatelabel
    spec:
      containers:
      - name: auth-service
        image: salif04/auth-service:1.0.4
        env:
        - name: PORT
          value: "3000"
        - name: MONGOCONNECTIONURI
          value: mongodb://azlan:password@auth-db:27017
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 216Mi
            cpu: "0.2"
