kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service-templatelabel
  type: LoadBalancer
  ports:
  - name: tcp
    protocol: TCP
    port: 80
    targetPort: 3000
